package com.evolting.playerms.utils.enums;

public enum Nationality {
    AFG("Afghanistan"),
    ALA("Åland Islands"),
    ALB("Albania"),
    DZA("Algeria"),
    ASM("American Samoa"),
    AND("Andorra"),
    AGO("Angola"),
    AIA("Anguilla"),
    ATA("Antarctica"),
    ATG("Antigua and Barbuda"),
    ARG("Argentina"),
    ARM("Armenia"),
    ABW("Aruba"),
    AUS("Australia"),
    AUT("Austria"),
    AZE("Azerbaijan"),
    BHS("Bahamas"),
    BHR("Bahrain"),
    BGD("Bangladesh"),
    BRB("Barbados"),
    BLR("Belarus"),
    BEL("Belgium"),
    BLZ("Belize"),
    BEN("Benin"),
    BMU("Bermuda"),
    BTN("Bhutan"),
    BOL("Bolivia"),
    BES("Bonaire, Sint Eustatius and Saba"),
    BIH("Bosnia and Herzegovina"),
    BWA("Botswana"),
    BRA("Brazil"),
    BRN("Brunei Darussalam"),
    BGR("Bulgaria"),
    BFA("Burkina Faso"),
    BDI("Burundi"),
    KHM("Cambodia"),
    CMR("Cameroon"),
    CAN("Canada"),
    CPV("Cape Verde"),
    CAF("Central African Republic"),
    TCD("Chad"),
    CHL("Chile"),
    CHN("China"),
    COL("Colombia"),
    COM("Comoros"),
    COG("Congo"),
    COD("Congo, Democratic Republic"),
    CRI("Costa Rica"),
    CIV("Côte d'Ivoire"),
    HRV("Croatia"),
    CUB("Cuba"),
    CYP("Cyprus"),
    CZE("Czech Republic"),
    DNK("Denmark"),
    DJI("Djibouti"),
    DMA("Dominica"),
    DOM("Dominican Republic"),
    ECU("Ecuador"),
    EGY("Egypt"),
    SLV("El Salvador"),
    GNQ("Equatorial Guinea"),
    ERI("Eritrea"),
    EST("Estonia"),
    ETH("Ethiopia"),
    FIN("Finland"),
    FRA("France"),
    DEU("Germany"),
    GHA("Ghana"),
    GRC("Greece"),
    GRD("Grenada"),
    GTM("Guatemala"),
    GIN("Guinea"),
    GNB("Guinea-Bissau"),
    GUY("Guyana"),
    HTI("Haiti"),
    HND("Honduras"),
    HKG("Hong Kong"),
    HUN("Hungary"),
    ISL("Iceland"),
    IND("India"),
    IDN("Indonesia"),
    IRN("Iran"),
    IRQ("Iraq"),
    IRL("Ireland"),
    ISR("Israel"),
    ITA("Italy"),
    JAM("Jamaica"),
    JPN("Japan"),
    JOR("Jordan"),
    KAZ("Kazakhstan"),
    KEN("Kenya"),
    KOR("Korea, Republic of"),
    PRK("Korea, DPR"),
    KWT("Kuwait"),
    LAO("Lao People's Democratic Republic"),
    LVA("Latvia"),
    LBN("Lebanon"),
    LBR("Liberia"),
    LBY("Libya"),
    LIE("Liechtenstein"),
    LTU("Lithuania"),
    LUX("Luxembourg"),
    MAC("Macao"),
    MKD("North Macedonia"),
    MDG("Madagascar"),
    MWI("Malawi"),
    MYS("Malaysia"),
    MDV("Maldives"),
    MLI("Mali"),
    MLT("Malta"),
    MHL("Marshall Islands"),
    MTQ("Martinique"),
    MRT("Mauritania"),
    MUS("Mauritius"),
    MEX("Mexico"),
    FSM("Micronesia"),
    MDA("Moldova"),
    MCO("Monaco"),
    MNG("Mongolia"),
    MNE("Montenegro"),
    MAR("Morocco"),
    MOZ("Mozambique"),
    MMR("Myanmar"),
    NAM("Namibia"),
    NRU("Nauru"),
    NPL("Nepal"),
    NLD("Netherlands"),
    NZL("New Zealand"),
    NIC("Nicaragua"),
    NER("Niger"),
    NGA("Nigeria"),
    NOR("Norway"),
    OMN("Oman"),
    PAK("Pakistan"),
    PLW("Palau"),
    PSE("Palestine"),
    PAN("Panama"),
    PNG("Papua New Guinea"),
    PRY("Paraguay"),
    PER("Peru"),
    PHL("Philippines"),
    POL("Poland"),
    PRT("Portugal"),
    QAT("Qatar"),
    ROU("Romania"),
    RUS("Russian Federation"),
    RWA("Rwanda"),
    KNA("Saint Kitts and Nevis"),
    LCA("Saint Lucia"),
    VCT("Saint Vincent and the Grenadines"),
    WSM("Samoa"),
    SMR("San Marino"),
    SAU("Saudi Arabia"),
    SEN("Senegal"),
    SRB("Serbia"),
    SYC("Seychelles"),
    SLE("Sierra Leone"),
    SGP("Singapore"),
    SVK("Slovakia"),
    SVN("Slovenia"),
    SLB("Solomon Islands"),
    SOM("Somalia"),
    ZAF("South Africa"),
    SSD("South Sudan"),
    ESP("Spain"),
    LKA("Sri Lanka"),
    SDN("Sudan"),
    SUR("Suriname"),
    SWE("Sweden"),
    CHE("Switzerland"),
    SYR("Syrian Arab Republic"),
    TWN("Taiwan"),
    TJK("Tajikistan"),
    TZA("Tanzania"),
    THA("Thailand"),
    TGO("Togo"),
    TTO("Trinidad and Tobago"),
    TUN("Tunisia"),
    TUR("Turkey"),
    UGA("Uganda"),
    UKR("Ukraine"),
    ARE("United Arab Emirates"),
    GBR("United Kingdom"),
    USA("United States"),
    URY("Uruguay"),
    UZB("Uzbekistan"),
    VEN("Venezuela"),
    VNM("Vietnam"),
    ZMB("Zambia"),
    ZWE("Zimbabwe");

    private final String fullName;

    Nationality(String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return fullName;
    }

    public static Nationality fromFullName(String fullName) {
        for (Nationality n : values()) {
            if (n.fullName.equalsIgnoreCase(fullName)) {
                return n;
            }
        }
        return null;
    }
}
